# Generated by Django 3.0.6 on 2020-12-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saarthi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='body',
            new_name='content',
        ),
    ]
