# Generated by Django 3.0.6 on 2020-12-06 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saarthi', '0003_url_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 6, 17, 36, 19, 472604), null=True),
        ),
    ]
